package capitals

import (
	"github.com/labstack/echo"
	"net/http"
)

var caps = map[string]string{
	"afghanistan":                       "kabul",
	"albania":                           "tirana",
	"algeria":                           "algiers",
	"andorra":                           "andorra la vella",
	"angola":                            "luanda",
	"antigua and barbuda":               "saint john's",
	"argentina":                         "buenos aires",
	"armenia":                           "yerevan",
	"australia":                         "canberra",
	"austria":                           "vienna",
	"azerbaijan":                        "baku",
	"the bahamas":                       "nassau",
	"bahrain":                           "manama",
	"bangladesh":                        "dhaka",
	"barbados":                          "bridgetown",
	"belarus":                           "minsk",
	"belgium":                           "brussels",
	"belize":                            "belmopan",
	"benin":                             "porto-novo",
	"bhutan":                            "thimphu",
	"bolivia":                           "la paz (administrative); sucre (judicial)",
	"bosnia and herzegovina":            "sarajevo",
	"botswana":                          "gaborone",
	"brazil":                            "brasilia",
	"brunei":                            "bandar seri begawan",
	"bulgaria":                          "sofia",
	"burkina faso":                      "ouagadougou",
	"burundi":                           "gitega (changed from bujumbura in december 2018)",
	"cambodia":                          "phnom penh",
	"cameroon":                          "yaounde",
	"canada":                            "ottawa",
	"cape verde":                        "praia",
	"central african republic":          "bangui",
	"chad":                              "n'djamena",
	"chile":                             "santiago",
	"china":                             "beijing",
	"colombia":                          "bogota",
	"comoros":                           "moroni",
	"congo, republic of the":            "brazzaville",
	"congo, democratic republic of the": "kinshasa",
	"costa rica":                        "san jose",
	"cote d'ivoire":                     "yamoussoukro (official); abidjan (de facto)",
	"croatia":                           "zagreb",
	"cuba":                              "havana",
	"cyprus":                            "nicosia",
	"czech republic":                    "prague",
	"denmark":                           "copenhagen",
	"djibouti":                          "djibouti",
	"dominica":                          "roseau",
	"dominican republic":                "santo domingo",
	"east timor (timor-leste)":          "dili",
	"ecuador":                           "quito",
	"egypt":                             "cairo",
	"el salvador":                       "san salvador",
	"equatorial guinea":                 "malabo",
	"eritrea":                           "asmara",
	"estonia":                           "tallinn",
	"ethiopia":                          "addis ababa",
	"fiji":                              "suva",
	"finland":                           "helsinki",
	"france":                            "paris",
	"gabon":                             "libreville",
	"the gambia":                        "banjul",
	"georgia":                           "tbilisi",
	"germany":                           "berlin",
	"ghana":                             "accra",
	"greece":                            "athens",
	"grenada":                           "saint george's",
	"guatemala":                         "guatemala city",
	"guinea":                            "conakry",
	"guinea-bissau":                     "bissau",
	"guyana":                            "georgetown",
	"haiti":                             "port-au-prince",
	"honduras":                          "tegucigalpa",
	"hungary":                           "budapest",
	"iceland":                           "reykjavik",
	"india":                             "new delhi",
	"indonesia":                         "jakarta",
	"iran":                              "tehran",
	"iraq":                              "baghdad",
	"ireland":                           "dublin",
	"israel":                            "jerusalem*",
	"italy":                             "rome",
	"jamaica":                           "kingston",
	"japan":                             "tokyo",
	"jordan":                            "amman",
	"kazakhstan":                        "astana",
	"kenya":                             "nairobi",
	"kiribati":                          "tarawa atoll",
	"korea, north":                      "pyongyang",
	"korea, south":                      "seoul",
	"kosovo":                            "pristina",
	"kuwait":                            "kuwait city",
	"kyrgyzstan":                        "bishkek",
	"laos":                              "vientiane",
	"latvia":                            "riga",
	"lebanon":                           "beirut",
	"lesotho":                           "maseru",
	"liberia":                           "monrovia",
	"libya":                             "tripoli",
	"liechtenstein":                     "vaduz",
	"lithuania":                         "vilnius",
	"luxembourg":                        "luxembourg",
	"macedonia":                         "skopje",
	"madagascar":                        "antananarivo",
	"malawi":                            "lilongwe",
	"malaysia":                          "kuala lumpur",
	"maldives":                          "male",
	"mali":                              "bamako",
	"malta":                             "valletta",
	"marshall islands":                  "majuro",
	"mauritania":                        "nouakchott",
	"mauritius":                         "port louis",
	"mexico":                            "mexico city",
	"micronesia, federated states of":   "palikir",
	"moldova":                           "chisinau",
	"monaco":                            "monaco",
	"mongolia":                          "ulaanbaatar",
	"montenegro":                        "podgorica",
	"morocco":                           "rabat",
	"mozambique":                        "maputo",
	"myanmar (burma)":                   "rangoon (yangon); naypyidaw or nay pyi taw (administrative)",
	"namibia":                           "windhoek",
	"nauru":                             "no official capital; government offices in yaren district",
	"nepal":                             "kathmandu",
	"netherlands":                       "amsterdam; the hague (seat of government)",
	"new zealand":                       "wellington",
	"nicaragua":                         "managua",
	"niger":                             "niamey",
	"nigeria":                           "abuja",
	"norway":                            "oslo",
	"oman":                              "muscat",
	"pakistan":                          "islamabad",
	"palau":                             "melekeok",
	"panama":                            "panama city",
	"papua new guinea":                  "port moresby",
	"paraguay":                          "asuncion",
	"peru":                              "lima",
	"philippines":                       "manila",
	"poland":                            "warsaw",
	"portugal":                          "lisbon",
	"qatar":                             "doha",
	"romania":                           "bucharest",
	"russia":                            "moscow",
	"rwanda":                            "kigali",
	"saint kitts and nevis":             "basseterre",
	"saint lucia":                       "castries",
	"saint vincent and the grenadines":  "kingstown",
	"samoa":                             "apia",
	"san marino":                        "san marino",
	"sao tome and principe":             "sao tome",
	"saudi arabia":                      "riyadh",
	"senegal":                           "dakar",
	"serbia":                            "belgrade",
	"seychelles":                        "victoria",
	"sierra leone":                      "freetown",
	"singapore":                         "singapore",
	"slovakia":                          "bratislava",
	"slovenia":                          "ljubljana",
	"solomon islands":                   "honiara",
	"somalia":                           "mogadishu",
	"south africa":                      "pretoria (administrative); cape town (legislative); bloemfontein (judiciary)",
	"south sudan":                       "juba",
	"spain":                             "madrid",
	"sri lanka":                         "colombo; sri jayewardenepura kotte (legislative)",
	"sudan":                             "khartoum",
	"suriname":                          "paramaribo",
	"swaziland":                         "mbabane",
	"sweden":                            "stockholm",
	"switzerland":                       "bern",
	"syria":                             "damascus",
	"taiwan":                            "taipei",
	"tajikistan":                        "dushanbe",
	"tanzania":                          "dar es salaam; dodoma (legislative)",
	"thailand":                          "bangkok",
	"togo":                              "lome",
	"tonga":                             "nuku'alofa",
	"trinidad and tobago":               "port-of-spain",
	"tunisia":                           "tunis",
	"turkey":                            "ankara",
	"turkmenistan":                      "ashgabat",
	"tuvalu":                            "vaiaku village, funafuti province",
	"uganda":                            "kampala",
	"ukraine":                           "kyiv",
	"united arab emirates":              "abu dhabi",
	"united kingdom":                    "london",
	"united states of america":          "washington, d.c.",
	"uruguay":                           "montevideo",
	"uzbekistan":                        "tashkent",
	"vanuatu":                           "port-vila",
	"vatican city (holy see)":           "vatican city",
	"venezuela":                         "caracas",
	"vietnam":                           "hanoi",
	"yemen":                             "sanaa",
	"zambia":                            "lusaka",
	"zimbabwe":                          "harare",
}

func ByCountry(c echo.Context) error {
	if x, ok := caps[c.Param("country")]; ok {
		return c.String(http.StatusOK, x)
	}

	return c.String(http.StatusNoContent, "country not found")
}

func All(c echo.Context) error {
	return c.JSON(http.StatusOK, caps)
}
